{{- if .Values.ingress.enabled -}}
{{- $fullName := include "huly.fullname" . -}}
{{- $frontName := include "huly.front.fullname" . -}}
{{- $svcPort := .Values.front.service.port | default 80 -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "huly.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "huly.front.fullname" $ }}
              port:
                number: {{ $.Values.front.service.port }}
        - path: /_accounts
          pathType: Prefix
          backend:
            service:
              name: {{ include "huly.account.fullname" $ }}
              port:
                number: {{ $.Values.account.service.port }}
        - path: /_collaborator
          pathType: Prefix
          backend:
            service:
              name: {{ include "huly.collaborator.fullname" $ }}
              port:
                number: {{ $.Values.collaborator.service.port }}
        - path: /_transactor
          pathType: Prefix
          backend:
            service:
              name: {{ include "huly.transactor.fullname" $ }}
              port:
                number: {{ $.Values.transactor.service.port }}
        - path: /eyJ
          pathType: Prefix
          backend:
            service:
              name: {{ include "huly.transactor.fullname" $ }}
              port:
                number: {{ $.Values.transactor.service.port }}
        - path: /_rekoni
          pathType: Prefix
          backend:
            service:
              name: {{ include "huly.rekoni.fullname" $ }}
              port:
                number: {{ $.Values.rekoni.service.port }}
        - path: /_stats
          pathType: Prefix
          backend:
            service:
              name: {{ include "huly.stats.fullname" $ }}
              port:
                number: {{ $.Values.stats.service.port }}
    {{- end }}
{{- end }}
