apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "huly.env.fullname" . }}
  labels:
    {{- include "huly.labels" . | nindent 4 }}
data:
  {{- include "toEnvVars" (dict "values" .Values.config.env "prefix" "" "isSecret" true) | nindent 4 }}
