apiVersion: v1
kind: Service
metadata:
  name: {{ include "huly.front.fullname" . }}
  labels: {{- include "huly.front.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: {{ .Values.front.service.containerPort }}
  selector: {{- include "huly.front.selectorLabels" . | nindent 4 }}
  type: {{ .Values.front.service.type | default "ClusterIP" }}
