apiVersion: v1
kind: Service
metadata:
  name: {{ include "huly.account.fullname" . }}
  labels: {{- include "huly.account.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.account.service.port }}
      targetPort: {{ .Values.account.service.containerPort }}
  selector: {{- include "huly.account.selectorLabels" . | nindent 4 }}
  type: {{ .Values.account.service.type | default "ClusterIP" }}
