---
{{- if .Values.rclone.secret.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.rclone.secret.name }}
stringData:
  {{ .Values.rclone.secret.key }}: |
    [s3]
    type = s3
    provider = {{ .Values.rclone.s3.provider | default "AWS" }}
    {{- with .Values.rclone.s3.endpoint }}
    endpoint = {{ . }}
    {{- end }}
    access_key_id = {{ required "Access key ID is required" .Values.rclone.s3.accessKeyId }}
    secret_access_key = {{ required "Secret access key is required" .Values.rclone.s3.secretAccessKey }}
    {{- with .Values.rclone.s3.region }}
    region = {{ . }}
    {{- end }}
    acl = private
    no_check_bucket = true
{{- end }}
